"""empty message

Revision ID: 1aeb4fde9398
Revises: 908c4405dfea
Create Date: 2017-10-12 09:56:34.741554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aeb4fde9398'
down_revision = '908c4405dfea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wechatuser', sa.Column('name', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wechatuser', 'name')
    # ### end Alembic commands ###
