"""empty message

Revision ID: 908c4405dfea
Revises: b036e2144f30
Create Date: 2017-10-07 19:44:20.007610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908c4405dfea'
down_revision = 'b036e2144f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wechatuser',
    sa.Column('openid', sa.Integer(), nullable=False),
    sa.Column('academy', sa.String(length=64), nullable=True),
    sa.Column('classname', sa.String(length=64), nullable=True),
    sa.Column('account', sa.Integer(), nullable=True),
    sa.Column('passwd', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('openid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wechatuser')
    # ### end Alembic commands ###
